# "Borrowed" the Windows part of the workflow from: https://github.com/CrowPlexus/Forever-Engine-Legacy/blob/master/.github/workflows/main.yml
# Android workflow stuff also "borrowed" from: https://github.com/MAJigsaw77/UTF/blob/main/.github/workflows/main.yml

name: Action build

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  windowsBuild:
    runs-on: windows-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Install & Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxe -cp ./actions -D analyzer-optimize -main Main --interp
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          haxelib run lime rebuild hxcpp
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7
          haxelib set hxcpp git

      - name: Build
        run: haxelib run lime build windows -D analyzer-optimize

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Maru-Funkin-Windows
          path: export/release/windows/bin
          if-no-files-found: error

  linuxBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Install & Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Installing Dependencies
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libvlc-dev libvlccore-dev vlc-bin vlc

      - name: Install Libraries
        run: |
          haxe -cp ./actions -D analyzer-optimize -main Main --interp
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          haxelib run lime rebuild hxcpp
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7
          haxelib set hxcpp git

      - name: Build
        run: haxelib run lime build linux -D analyzer-optimize

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Maru-Funkin-Linux
          path: export/release/linux/bin
          if-no-files-found: error
  
  androidBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Install & Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r21e

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Libraries
        run: |
          haxe -cp ./actions -D analyzer-optimize -main Main --interp
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          haxelib run lime rebuild hxcpp
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7
          haxelib set hxcpp git
      
      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build
        run: haxelib run lime build android -D analyzer-optimize

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Maru-Funkin-Android
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error
